name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run:  echo ${{ secrets.DOCKERPAT }} | docker login -u bhhoang
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nanika/ns3:latest
    - name: Publish to Dockerhub
      run: docker push nanika:ns3:latest
